git:
  depth: 2000

language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
    - os: osx
      osx_image: xcode10.1
      compiler: clang
      sudo: false

cache:
  - ccache

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; fi
#  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get  --no-install-suggests --no-install-recommends --force-yes install p7zip-full; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y build-essential libssl-dev libsqlcipher-dev libbz2-dev libmicrohttpd-dev libsqlite3-dev libupnp-dev pkg-config qt5-default libxss-dev qtmultimedia5-dev libqt5x11extras5-dev libqt5designer5 libxapian-dev qttools5-dev libgnome-keyring-dev; fi

  - if [ $TRAVIS_OS_NAME == osx ]; then brew update ; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install ccach; export PATH="/usr/local/opt/ccache/libexec:$PATH" ; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install qt5; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew link --force qt5 ; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install openssl miniupnpc libmicrohttpd sqlcipher xapian; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install p7zip; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then npm install -g appdmg; fi

  - wget https://github.com/Tencent/rapidjson/archive/v1.1.0.tar.gz
  - tar -xf v1.1.0.tar.gz
  - if [ $TRAVIS_OS_NAME == osx ]; then cp -r rapidjson-1.1.0/include/rapidjson/ /usr/local/include/rapidjson ; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo cp -r rapidjson-1.1.0/include/rapidjson/ /usr/include/rapidjson ; fi

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "auwuhxelaMriNaXzT8I03xrh1s+STicNyNToOWFCAYKxkWWQ4WeaCO6kRDmQrejhizMUILGU+s4FrWTEhDsviftGAF86EgzxxbSBfsHHAP4t2C0pcXX8/WxEoh1IrUs7iGCIpl7O2cvWqGidc20ROeptSEd1uQgkHnn14D9A2YmXf8g52PzqivKkb6HKfkVTPdmNJkMBT5eDtEw6DIk+DvnvRo6b6uanvVAKS9CBwXOdA3rLzaD9bz0LrdL9X1CNoTkGROyez0Lsc4zTr70id2Xfp1MMmJAV6hgQy+iwE37wRyrxJf3dkh5SUAAMUC9Xnvh/iBKNQKdQGhj2WGcV7GZV9k6u9DA1w2H0kcrwt9KHUXdhEQ67yr6Boa9ZFwdDb5VIOtC6iHAoDZXharHhiuxi0K/bCtwNAajrMjBCm9mWhEKvtoxUUYxAJajhJkkO3ERaOU3zHE+06esDzGozd2YOEH8a74HhYy4xvhR05Yj00hAWLS2kIaUITiqmBf6Yuh5XwH7KCDcapxF59ROWqyicdwtbfWpvN8IvFuGKyxYuEfoT8WxZ4lZpo4Q9CrTB7gedJYJxYNfZE/okWoFBb4cpPI94PHo3DZPR7lVyQ60RNyeR0nOeqf8NW8cBT1G4jw3u1LEyAdyvup+54aALw0DCVyoDojSXB8s+AlQG2JE="

addons:
  coverity_scan:
    project:
      name: "RetroShare/RetroShare"
      description: "RetroShare Build submitted via Travis CI"
    build_command_prepend: "qmake CONFIG+=no_sqlcipher; make clean"
    build_command: " make -j4"
    branch_pattern: coverity_scan

before_script:
  - if [ $TRAVIS_OS_NAME == linux ]; then qmake QMAKE_CC=$CC QMAKE_CXX=$CXX; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then qmake QMAKE_CC=$CC QMAKE_CXX=$CXX CONFIG+=rs_macos10.14 INCLUDEPATH+=/usr/local/opt/openssl/include/ INCLUDEPATH+=$(find /usr/local/Cellar/sqlcipher/*/include | headn -n 1) INCLUDEPATH+=$(find /usr/local/Cellar/libmicrohttpd/*/include | head -n 1) QMAKE_LIBDIR+=/usr/local/opt/openssl/lib/ QMAKE_LIBDIR+=$(find /usr/local/Cellar/libmicrohttpd/*/lib | head -n 1) QMAKE_LIBDIR+=$(find /usr/local/Cellar/sqlcipher/*/lib | head -n 1); fi

script:
  - if [ $TRAVIS_OS_NAME == linux ] && [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make -j2; fi
  - if [ $TRAVIS_OS_NAME == osx ] && [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then /Applications/Xcode.app/Contents/Developer/usr/bin/make -j2; fi


after_success:
  - if [ $TRAVIS_OS_NAME == osx ] ; then  cd retroshare-gui/src/; rm -rf moc; rm -rf obj; rm -rf qrc ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then  mv retroshare.app unseenp2p.app; macdeployqt unseenp2p.app -qmldir=../src/  -dmg; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then  mv unseenp2p.dmg UnseenP2P-0.6.6.dmg; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then  appdmg json-path UnseenP2P-0.6.6.dmg; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then  7z a UnseenP2P-0.6.6_macos.zip UnseenP2P-0.6.6.dmg; cd ../..; fi

#  - if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then rake deploy; fi

#branches:
#  only:
#    - master
#    - travis

#deploy:
#  - provider: releases
#    api_key: $TOKEN
#    file:
#      - retroshare-gui/src/UnseenP2P-0.6.6_macos.zip
#    overwrite: true
#    skip_cleanup: true
#    on:
#      all_branches: true
#      tags: true
#      condition: $TRAVIS_OS_NAME = osx
  #- provider: releases
  #  api_key: $TOKEN
  #  file:
  #    - build/linux/gcc/x86_64/release/YourApp_${TRAVIS_TAG}_linux_x86_64_portable.zip
  #    - installer/linux/YourApp_${TRAVIS_TAG}_linux_x86_64_installer
  #  overwrite: true
  #  skip_cleanup: true
  #  on:
  #    tags: false
  #    condition: $TRAVIS_OS_NAME = linux


notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#retroshare"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
      - "Message: %{commit_message}"
      - "Commit details: %{compare_url}"
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/9502afd22ca6c8e85fb3
#    on_success: change
#    on_failure: always
#    on_start: always

#env:
#  - RVM=2.0.0 LANG="en_US.UTF-8"
